myblog/blog/urls.py
from django.urls import path
from . import  views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('article/<int:article_id>/',views.article_page,name='article_page'),
    path('edit/',views.edit_page,name = 'edit_page'),
    path('edit/action/',views.action_page,name='edit_action'),
    path('edit/delete/<int:article_id>/',views.edit_delete,name = 'edit_delete'),
    path('edit/change/<int:article_id>/',views.edit_change,name = 'edit_change'),
    path('edit/tocha/<int:article_id>/',views.to_change,name = 'to_change'),
    path('machine/',views.machine,name = 'machine'),
    path('xiaohang/',views.first_page, name = 'first_page'),
    path('jinglingqiu/',views.cssdemo1,name = 'jinglingqiu'),
    path('thetime/',views.thetime,name = 'thetime'),
    path('game_2048/',views.game_2048,name = 'game_2048'),
    path('weather/',views.cssdemo2,name = 'weather'),

]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('mooc/',include(('mooc.urls','mooc'),namespace='mooc')),
    path('newblog/',include(('newblog.urls','newblog'),namespace='newblog'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.IMG_URL, document_root=settings.IMG_ROOT)

myblog/newblog/urls.py
from django.urls import path
from . import  views

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('show/',views.essay_content,name = 'show'),
    path('essay/',views.get_index_page,name = 'essay'),
    path('detail/<int:essay_id>/',views.detail,name = 'detail'),

]

myblog/newblog/models.py
from django.db import models

# Create your models here.

class Essay(models.Model):
    """
    文章标题
    文章摘要
    文章内容
    文章唯一id
    文章发布日期
    """
    essay_id = models.AutoField(primary_key=True)
    title = models.TextField()
    brief_content = models.TextField()
    content =  models.TextField()
    publish_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return  self.title

myblog/newblog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from django.core.paginator import Paginator


def index(request):
    return HttpResponse('<h1>hello world<h1>')


def essay_content(requset):
    essay = models.Essay.objects.all()[0]
    return render(requset, 'newblog/show.html', {'essay': essay})


def get_index_page(request):
    page = request.GET.get('page')
    if page :
        page = int(page)
    else :
        page = 1
    essays = models.Essay.objects.all()
    if len(essays) >= 5:
        top_list = models.Essay.objects.order_by('-publish_date')[:5]
    else :
        top_list = models.Essay.objects.order_by('-publish_date')[:len(essays)]
    paginator = Paginator(essays,3)
    page_num = paginator.num_pages
    print('page_num',paginator.num_pages)
    page_article_list = paginator.page(page)
    if page_article_list.has_next():
        next_page = page+1
    else :
        next_page = page

    if page_article_list.has_previous():
        previous = page -1
    else :
        previous = page

    return render(request, 'newblog/index.html', {'essays': page_article_list,
                                                  'page_num':range(1,page_num+1),
                                                  'curr_page':page,
                                                  'next_page':next_page,
                                                  'previous':previous,
                                                  'top_list':top_list})


def detail(request, essay_id):
    #essay = models.Essay.objects.get(essay_id=essay_id)
    #section_list = essay.content.split('\n')
    all_essay = models.Essay.objects.all()
    essay = None
    previous_index = 0
    next_index = 0
    for index,curr_essay in enumerate(all_essay):
        if index == 0:
            previous_index = 0
            next_index = 1
        elif index == len(all_essay) -1 :
            previous_index = index -1
            next_index = index
        else :
            previous_index = index -1
            next_index = index +1
        if curr_essay.essay_id == essay_id:
            essay = curr_essay
            previous_essay = all_essay[previous_index]
            next_essay = all_essay[next_index]
            break
    section_list = essay.content.split('\n')

    return render(request, 'newblog/detail.html', {'essay': essay,'section_list':section_list,
                                                   'previous_essay':previous_essay,'next_essay':next_essay})

myblog/newblog/templates/newblog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章内容</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>

    <div class="container page-header">
        <h1>{{essay.title}}</h1>
    </div>
    <div class="container body-main">

        <div>
            {% for section in section_list %}
            <p>{{section}}</p>
            {% endfor %}

        </div>

    </div>
<div>
    <nav aria-label="...">
        <ul class="pager">
            <li><a href="/newblog/detail/{{previous_essay.essay_id}}/">上一篇：{{previous_essay.title}}</a></li>
            <li><a href="/newblog/detail/{{next_essay.essay_id}}/">下一篇：{{next_essay.title}}</a></li>
        </ul>
    </nav>
</div>
</body>
</html>

myblog/newblog/templates/newblog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>博客首页</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container page-header">
    <h1>我的文章
        <small>--by 小航</small>
    </h1>
</div>
<div class="container page-body">
    <div class="col-md-9" role="main">
        <div class="body-main">
            {% for essay in essays %}
            <div>
                <h2><a href="{% url 'newblog:detail' essay.essay_id %}">{{essay.title}}</a></h2>
                <p>{{essay.brief_content}}</p>
            </div>
            {% endfor %}
        </div>
        <div class="body-footer">
            <div class = "col-md-4 col-md-offset-3">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="/newblog/essay?page={{previous}}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% for num in page_num  %}
                        <li><a href="/newblog/essay?page={{num}}">{{num}}</a></li>
                        {% endfor %}
                        <li>
                            <a href="/newblog/essay?page={{next_page}}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

    </div>
    <div class="col-md-3" role="complementary">
        <div>
            <h2>最新文章</h2>
            {% for essay in top_list %}
            <h4><a href="{% url 'newblog:detail' essay.essay_id %}">{{essay.title}}</a></h4>
            {% endfor %}
        </div>
    </div>
</div>

</body>
</html>

myblog/newblog/templates/newblog/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<h1>{{essay.title}}</h1>
<h3>{{essay.brief_content}}</h3>
<span>--------------------------------------------</span>
<h5>{{essay.content}}</h5>
<span>--------------------------------------------</span>
<h6>{{essay.publish_date}}</h6>
</body> 
</html>