myblog/blog/urls.py
from django.urls import path
from . import  views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('article/<int:article_id>/',views.article_page,name='article_page'),
    path('edit/',views.edit_page,name = 'edit_page'),
    path('edit/action/',views.action_page,name='edit_action'),
    path('edit/delete/<int:article_id>/',views.edit_delete,name = 'edit_delete'),
    path('edit/change/<int:article_id>/',views.edit_change,name = 'edit_change'),
    path('edit/tocha/<int:article_id>/',views.to_change,name = 'to_change'),
    path('machine/',views.machine,name = 'machine'),
    path('xiaohang/',views.first_page, name = 'first_page'),
    path('jinglingqiu/',views.cssdemo1,name = 'jinglingqiu'),
    path('thetime/',views.thetime,name = 'thetime'),
    path('game_2048/',views.game_2048,name = 'game_2048'),
    path('weather/',views.cssdemo2,name = 'weather'),

]

myblog/mooc/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('index/', views.index, name='index'),
    path('hello/',views.hello,name = 'hello'),
    path('msggate/',views.msgproc, name = 'msggate'),
    path('upload/',views.uploadImg, name = 'upload'),
    path('show/',views.showImg, name='show'),
    path('delete/<int:img_id>/', views.delete, name = 'delete'),
    path('html1/',views.html1,name = 'hetml1'),
    path('html2/',views.html2,name = 'hetml2'),
    path('html3/',views.html3,name = 'hetml3'),
    path('html5/',views.html5,name = 'hetml5'),
    path('html6/',views.html6,name = 'hetml6'),
    path('html7/',views.html7,name = 'html7'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.IMG_URL, document_root=settings.IMG_ROOT)

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('mooc/',include(('mooc.urls','mooc'),namespace='mooc')),
    path('newblog/',include(('newblog.urls','newblog'),namespace='newblog'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.IMG_URL, document_root=settings.IMG_ROOT)

myblog/mooc/models.py
from django.db import models

# Create your models here.

class Img(models.Model):
    img = models.ImageField(upload_to='img')
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

myblog/mooc/views.py
from django.shortcuts import render
from PIL import Image
import numpy as np
from .models import Img
from . import models
import  os,sys
from datetime import datetime
sys.path.append("..")
from newblog import models as md




# Create your views here.

def index(request):
    post_list = md.Essay.objects.all()
    return render(request, 'mooc/index.html', {'post_list': post_list})

def hello(request):
    return  render(request,'mooc/hello.html')

def msgproc(request):
    datalist = []
    if request.method == "POST":
        usera = request.POST.get("usera", None)
        userb = request.POST.get("userb", None)
        msg = request.POST.get("msg", None)
        time = datetime.now()
        with open('msgdata.txt', 'a+') as f:
            f.write("{}--{}--{}--{}--\n".format(userb, usera, \
                                                msg, time.strftime("%Y-%m-%d %H:%M:%S")))
    if request.method == "GET":
        userc = request.GET.get("userc", None)
        if userc != None:
            with open("msgdata.txt", "r") as f:
                cnt = 0
                for line in f:
                    linedata = line.split('--')
                    if linedata[0] == userc:
                        cnt = cnt + 1
                        d = {"usera": linedata[1], "msg": linedata[2] \
                            , "time": linedata[3]}
                        datalist.append(d)
                    if cnt >= 10:
                        break
    return  render(request, "mooc/MsgSingleWeb.html",{"data":datalist})


def uploadImg(request):
    if request.method == 'POST':
        # print(type(request.FILES.get('img')))
        img = request.FILES.get('img')
        name = request.FILES.get('img').name
        new_img = Img(img=img, name=name)
        new_img.save()
        path = os.path.abspath('.')
        picture_url = new_img.img.url
        path2 = path + picture_url
        picture_change(path2)
    return render(request, 'mooc/uploading.html')


def showImg(request):
    imgs = Img.objects.all()
    content = {
        'imgs': imgs,
    }
    return render(request, 'mooc/showing.html', content)


def delete(request, img_id):
    picture = models.Img.objects.get(pk=img_id)
    models.Img.objects.filter(pk=img_id).delete()
    path = os.path.abspath('.')
    picture_url = picture.img.url
    path2 = path + picture_url
    os.remove(path2)

    imgs = Img.objects.all()
    content = {
        'imgs': imgs,
    }
    return render(request, 'mooc/showing.html', content)


def picture_change(pictureUrl):
    # 为了便于文件的导入，可以使用相对路径，将文件和程序放在同一个文件夹下
    vec_el = np.pi / 2.2
    vec_az = np.pi / 4.
    depth = 10.
    im = Image.open(pictureUrl).convert('L')
    a = np.asarray(im).astype('float')
    grad = np.gradient(a)
    grad_x, grad_y = grad
    grad_x = grad_x * depth / 100.
    grad_y = grad_y * depth / 100.
    dx = np.cos(vec_el) * np.cos(vec_az)
    dy = np.cos(vec_el) * np.sin(vec_az)
    dz = np.sin(vec_el)
    A = np.sqrt(grad_x ** 2 + grad_y ** 2 + 1.)
    uni_x = grad_x / A
    uni_y = grad_y / A
    uni_z = 1. / A
    a2 = 255 * (dx * uni_x + dy * uni_y + dz * uni_z)
    a2 = a2.clip(0, 255)
    im2 = Image.fromarray(a2.astype('uint8'))
    im2.save(pictureUrl)

#html test
def html1(request):
    return  render(request,'mooc/html1.html')

def html2(request):
    return  render(request,'mooc/html2.html')

def html3(request):
    return  render(request,'mooc/html3.html')

def html5(request):
    return  render(request,'mooc/html5.html')

def html6(request):
    return  render(request,'mooc/html6.html')

def html7(request):
    return  render(request,'mooc/html7.html')

myblog/mooc/templates/mooc/MsgSingleWeb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>云端留言板</title>
</head>
<body>
    <h1>提交留言功能</h1>
    <form action="/mooc/msggate/" method="post">
        {% csrf_token %}
        发送方 <input type="text" name = "usera"> <br>
        接收方 <input type="text" name = "userb"> <br>
        消息文 <input type="text" name = "msg"> <br>
        <input type="submit" value="提交"> <br>
    </form>

    <h1>获取留言功能</h1>
    <form action="/mooc/msggate/" method="get">
        接收方 <input type="text" name = "userc"> <br>
        <input type="submit" value="留言获取">
    </form>

    <table border="1">
        <thead>
            <th>留言时间</th>
            <th>留言来源</th>
            <th>留言信息</th>
        </thead>
        <br>
        <tbody>
            {% for line in  data%}
            <tr>
                <td>{{ line.time }}</td>
                <td align = "center">{{ line.usera }}</td>
                <td>{{ line.msg }}</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>

</body>
</html>

myblog/mooc/templates/mooc/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A layout example that shows off a blog page with a list of posts.">

    <title>Xu Hang Blog</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/blog.css">
</head>
<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title">Xu Hang Blog</h1>
            <h2 class="brand-tagline">雪忆 - Snow Memory</h2>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="pure-button" href="https://github.com/github807160646">Github</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="https://music.163.com/#/user/home?id=254972726">Music</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal pure-menu-open">
                    <ul>
                        <li><a href="http://andrewliu.tk/about/">About Me</a></li>
                        <li><a href="http://twitter.com/yuilibrary/">Twitter</a></li>
                        <li><a href="http://github.com/yahoo/pure/">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

myblog/mooc/templates/mooc/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script>
        function displayDate() {
            document.getElementById("time").innerHTML=Date();
        }
    </script>
</head>
<body>
hello world
<p id ="time">这里将显示时间</p>
<button type="button" onclick="displayDate() ">点击</button>
</body>
</html>

myblog/mooc/templates/mooc/html01.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>布局</title>
    <style type="text/css">
        body{
            margin: 0; padding: 0;
        }
        .main{
            width: 800px; height:300px;background: #cccccc; margin:0 auto;
        }
        .top{ height:100px;
            background: blue; }
        .foot{ width:800px;
            height: 100px;
            background: #900;
            margin: 0 auto;}
    </style>
</head>
<body>
    <!--一列布局-->
    <div class="top"></div>
    <div class = "main"></div>
    <div class="foot"></div>
</body>
</html>

myblog/mooc/templates/mooc/html2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>布局</title>
    <style type="text/css">
        body{ margin: 0; padding: 0;}
        .main{ width:800px;margin: 0 auto; }
        .left{width:220px;height:500px; float: left;background: red ;}
        .right{ width :580px; height:500px ; float:right;background:blue;}
    </style>
</head>
<body>
<div class="main">
    <div class="left"></div>
    <div class="right"></div>
</div>
</body>
</html>

myblog/mooc/templates/mooc/html3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>布局</title>
    <style type="text/css">
        body{ margin: 0; padding: 0;}
        /*.main{ width:800px;margin: 0 auto; }*/
        .left{width:200px;height:500px; background: red ;position: absolute; left:0 ; top: 0;}
        .middle{height: 500px; background:#cccccc; margin: 0 310px 0 210px;text-align: center;}
        .right{ width :300px; height:500px ; background:blue;position: absolute; top: 0; right: 0;}
    </style>
</head>
<body>
<div class="main">
    <div class="left"></div>
    <div class="middle">浣溪沙 <br>
                        谁念西风独自凉？<br>
                        萧萧黄叶闭疏窗。<br>
                        沉思往事立残阳。<br>
                        被酒莫惊春睡重,<br>
                        赌书消得泼茶香。<br>
                        当时只道是寻常。</div>
    <div class="right"></div>
</div>
</body>
</html>

myblog/mooc/templates/mooc/html4.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>混合布局</title>
    <style type="text/css">
        body{
            margin: 0; padding: 0;
        }
        .main{
            width: 800px; height:600px;background: #cccccc; margin:0 auto;
        }
        .top{ height:100px;
            background: blue; }
        .foot{ width:800px;
            height: 100px;
            background: #ffeba5;
            margin: 0 auto;}
        .left{width:200px;height:600px;background: #8278ff; float: left}
        .right{width:600px;height: 600px ; background: #393bff;float: right}
        .sub_l{width:400px;height: 600px;background: cornflowerblue;float: left}
        .sub_r{width: 200px;height: 600px;background: deepskyblue ;float: right}
        .head{width: 800px;height: 100px;background: #cccccc;margin: 0 auto; }
    </style>
</head>
<body>
    <!--一列布局-->
    <div class="top">
        <div class="head"></div>
    </div>
    <div class = "main">
        <div class="left"></div>
        <div class="right">
            <div class="sub_l"></div>
            <div class="sub_r"></div>
        </div>
    </div>
    <div class="foot"></div>
</body>
</html>

myblog/mooc/templates/mooc/html5.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>布局实例</title>
    <style type="text/css">
        .main{width: 800px; height: 300px; background: #cccccc; position: relative;margin: 0 auto}
        .left{width: 120px;height: 300px; background: deepskyblue;float: left;}
        .right{width: 640px;height: 300px; background: dimgray ;float: right;padding: 0 20px}
        .img{position: relative; left: 10px; top: 25px;}
        .title{font-weight: bold;font-size: 15px;margin: 20px 0;}
        .time{position: absolute;top:20px;right:10px; font-size: 12px}

    </style>
</head>
<body>
<div class="main">
    <div class="left">
        <!--django图片引用问题，需要设置绝对路径在settings里面进行设置-->
        <img class="img" src="/img/flower.jpg" width="100px" height="75px">
    </div>
    <div class="right">
        <h6 class="title">慕尼黑工业大学</h6>
        <p class="menu">历史悠久的德国王牌理工类大学</p>
        <!--时间需要使用绝对定位-->
        <span class="time">五小时前</span>
    </div>
</div>
</body>
</html>

myblog/mooc/templates/mooc/html6.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>菜单制作</title>
    <style type="text/css">
        *{margin: 0;padding: 0;font-size: 14px;}
        ul{list-style: none;width: 100px;position: relative;left: 20px;}
        li{height: 30px;line-height: 30px;width: 100px;background-color: #cac7b3;margin-bottom: 1px;
        text-align: center;}
        a{text-decoration: none;display: block;}
        a:hover{background-color: red;}
    </style>
</head>
<body>
<ul>
    <li><a href="#">首页</a></li>
    <li><a href="#">新闻快讯</a></li>
    <li><a href="#">产品展示</a></li>
    <li><a href="#">售后服务</a></li>
    <li><a href="#">联系我们</a></li>
</ul>
</body>
</html>

myblog/mooc/templates/mooc/html7.html
<!DOCTYPE html>
<html>
<head>
	<title>太极</title>
	<style type="text/css">
		div{

			padding: 0;
			margin: 0;
		}
		body{
			text-align: center;
		}
		.outer{
			margin-top:100px;
			display: inline-block;
			width: 400px;
			height: 400px;
			transition: all 1s;

		}
		.lf{
			border-left:  1px solid black;
			float: left;
			border-radius: 400px 0 0 400px;
			width: 199px;
			height: 400px;
			background-color: black;
			position: relative;
		}
		.ri{
			border-right:  1px solid black;
			border-radius: 0 400px 400px 0;
			float: left;
			width: 199px;
			height: 400px;
			background-color: #FFF;
			position: relative;
		}
		.top{
			width: 100px;
			height: 200px;
			background-color: #FFF;
			position: absolute;
			top: 0;
			right: 0;
			border-radius: 200px 0 0 200px;
		}
		.btm{
			width: 100px;
			height: 200px;
			background-color: black;
			position: absolute;
			bottom: 0;
			left: 0;
			border-radius: 0 200px 200px 0;
		}
		.to-in{
			width: 40px;
			height: 40px;
			background-color: black;
			position: absolute;
			right: 0;
			top: 80px;
			margin-right: -20px;
			visibility:visible;
			z-index: 4;
			border-radius: 40px;
		}
		.bt-in{
			width: 40px;
			height: 40px;
			background-color: white;
			position: absolute;
			left: 0;
			top: 80px;
			margin-left: -20px;
			visibility:visible;
			z-index: 4;
			border-radius: 40px;
		}
		.outer:hover{
			transform:rotate(-360deg);
		}
	</style>
</head>
<body>
	<div class="outer">
		<div class="lf">
			<div class="top">
				<div class="to-in"></div>
			</div>
		</div>
		<div class="ri">
			<div class="btm">
				<div class="bt-in"></div>
			</div>
		</div>
	</div>

</body>
</html>

myblog/mooc/templates/mooc/index.html
{% extends "mooc/base.html" %}

{% block content %}
<div class="posts">
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}</h2>

                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time }}</a> <a class="post-category post-category-js" href="#">{{ post.category }}</a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content }}
                    </p>
                </div>
        </section>
    {% endfor %}
</div><!-- /.blog-post -->
{% endblock %}

myblog/mooc/templates/mooc/showing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:index' %}">返回列表</a></h1>
<span>-----------------------------------------------</span>
<br>
{% for img in imgs %}
<img src="{{ img.img.url }}" /><br>
<h1><a href="{% url 'mooc:delete' img.id %}">删除</a></h1>
<br>
{% endfor %}
</body>
</html>

myblog/mooc/templates/mooc/uploading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>图片水墨风处理</h1>
<span>------------------------------------</span>
<br><br>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<input type="file" name="img">
<button type="submit">上传</button>
<br><br>
<span>------------------------------------</span>
<h1><a href="{% url 'mooc:show'%}">图片展示</a></h1>
</form>
</body>
</html>