myblog/blog/urls.py
from django.urls import path
from . import  views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('article/<int:article_id>/',views.article_page,name='article_page'),
    path('edit/',views.edit_page,name = 'edit_page'),
    path('edit/action/',views.action_page,name='edit_action'),
    path('edit/delete/<int:article_id>/',views.edit_delete,name = 'edit_delete'),
    path('edit/change/<int:article_id>/',views.edit_change,name = 'edit_change'),
    path('edit/tocha/<int:article_id>/',views.to_change,name = 'to_change'),
    path('machine/',views.machine,name = 'machine'),
    path('xiaohang/',views.first_page, name = 'first_page'),
    path('jinglingqiu/',views.cssdemo1,name = 'jinglingqiu'),
    path('thetime/',views.thetime,name = 'thetime'),
    path('game_2048/',views.game_2048,name = 'game_2048'),
    path('weather/',views.cssdemo2,name = 'weather'),

]

myblog/mooc/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('index/', views.index, name='index'),
    path('hello/',views.hello,name = 'hello'),
    path('msggate/',views.msgproc, name = 'msggate'),
    path('upload/',views.uploadImg, name = 'upload'),
    path('show/',views.showImg, name='show'),
    path('delete/<int:img_id>/', views.delete, name = 'delete'),
    path('html1/',views.html1,name = 'hetml1'),
    path('html2/',views.html2,name = 'hetml2'),
    path('html3/',views.html3,name = 'hetml3'),
    path('html5/',views.html5,name = 'hetml5'),
    path('html6/',views.html6,name = 'hetml6'),
    path('html7/',views.html7,name = 'html7'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.IMG_URL, document_root=settings.IMG_ROOT)

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include(('blog.urls','blog'),namespace='blog')),
    path('mooc/',include(('mooc.urls','mooc'),namespace='mooc')),
    path('newblog/',include(('newblog.urls','newblog'),namespace='newblog'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.IMG_URL, document_root=settings.IMG_ROOT)

myblog/newblog/urls.py
from django.urls import path
from . import  views

urlpatterns = [
    path('index/',views.index,name = 'index'),
    path('show/',views.essay_content,name = 'show'),
    path('essay/',views.get_index_page,name = 'essay'),
    path('detail/<int:essay_id>/',views.detail,name = 'detail'),

]

myblog/blog/models.py
from django.db import models


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32, default='title')
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

myblog/blog/views.py
from django.shortcuts import render

from . import models

def first_page(request):
    return  render(request,'blog/first_page.html')

def machine(request):
    return render(request, 'blog/machine_learn.html')

def cssdemo1(request):
    return  render(request , 'blog/css_demo1.html')


def thetime(request):
    return  render(request, 'blog/thetime/index.html')

def game_2048(request):
    return render(request, 'blog/game_2048/index.html')

def cssdemo2(request):
    return  render(request,"blog/weather.html")


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    sections = article.content.split('\n')
    return render(request, 'blog/article_page.html', {'article': article, 'sections': sections})


def to_change(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/change_page.html', {'article': article})


def edit_page(request):
    return render(request, 'blog/edit_page.html')


def edit_delete(request, article_id):
    models.Article.objects.filter(pk=article_id).delete()
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def edit_change(request, article_id):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    models.Article.objects.filter(pk=article_id).update(title=title)
    models.Article.objects.filter(pk=article_id).update(content=content)
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def action_page(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    models.Article.objects.create(title=title, content=content)
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
<h1>{{article.title}}</h1>
<br>
{% for section in sections %}
<h3>{{section}}</h3>
{% endfor %}
<br><br>
<a href="{% url 'blog:to_change'  article.id %}">修改文章</a>
<a href="{% url 'blog:index' %}">返回列表</a>
</body>
</html>

myblog/blog/templates/blog/change_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit page</title>
</head>
<body>
<form action="{% url 'blog:edit_change' article.id %}" method="post">
    {% csrf_token %}
    <label>文章标题
    <input type="text" name="title" value="{{article.title}}">
    </label>
    <br><br>
    <label>文章内容</label><br>
    <textarea rows="10" cols="50" name="content" >{{article.content}}</textarea>
    <br>
    <input type="submit" name="修改">
</form>
</body>
</html>

myblog/blog/templates/blog/css_demo1.html
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>精灵球</title>
	<style type="text/css">
		.draw{
			margin: 0 auto;
			width: 0;
			height: 0;
			color: black;
			border-bottom: 100px solid  white ;
			border-top: 0 solid white;
			border-left: 100px solid red;
			border-right: 0 solid white;
		}
		.outer{
			border:2px solid black;
			width: 100px;
			height: 100px;
			margin: 0 auto;
			border-radius: 50px;
			overflow: hidden;
			position: relative;
		}
		.center{
			border:2px solid black;
			width: 20px;
			height: 20px;
			margin: 0 auto;
			border-radius: 10px;
			position: absolute ;
			left: 40px;
			top: 40px;
			background: white;
		}
		@keyframes change {
			0%{ color:red; }25%{color:yellow;}50%{color:blue;}75%{color:green;}100%{color:purple;}
		}


		.main{
			margin: 20px auto; text-align: center;font-size: 40px ;
			animation:change 5s infinite;
			-webkit-animation:change 5s infinite;
		}

	</style>
</head>
<body>
	<div class = "main">纯css3实现精灵球图片</div>
	<div class="outer">
		<div class="draw"></div>
		<div class="center"></div>
	</div>
</body>
</html>

myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit page</title>
</head>
<body>
<form action="{% url 'blog:edit_action'%}" method="post">
    {% csrf_token %}
    <label>文章标题
    <input type="text" name="title" value="{{article.title}}">
    </label>
    <br><br>
    <label>文章内容</label><br>
    <textarea rows="10" cols="50" name="content" >{{article.content}}</textarea>
    <br>
    <input type="submit" name="提交">
</form>
</body>
</html>

myblog/blog/templates/blog/first_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<h1>徐航的个人主页</h1>
<div>--------------------------------------------------</div>
<h2>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <span>::</span>
    <a href="{% url 'blog:index' %}" target="_blank">第一个博客样式</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>
    <span>::</span>
    <a href="https://music.163.com/#/user/home?id=254972726" target="_blank">网易云音乐</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
    <span>::</span>
    <a href="https://code.ziqiangxuetang.com/django/django-tutorial.html" target="_blank">Django学习</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
    <span>::</span>
    <a href="{% url 'mooc:upload' %}" target="_blank">图片水墨风处理</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <span>::</span>
    <a href="{% url 'newblog:essay' %}" target="_blank">另一个博客样式</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
    <span>::</span>
    <a href="{% url 'blog:machine' %}" target="_blank">机器学习</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <span>::</span>
    <a href="{% url 'mooc:index' %}" target="_blank">第三个博客样式</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
    <span>::</span>
    <a href="{% url 'blog:jinglingqiu' %}" target="_blank">精灵球</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
    <span>::</span>

    <a href="{% url 'blog:thetime' %}" target="_blank">绚丽时钟效果</a>
    </h2>
    <h2>
    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
    <span>::</span>

    <a href="{% url 'blog:weather' %}" target="_blank">天气</a>
</h2>
<h2>
    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
    <span>::</span>
    <a href="{% url 'mooc:html7' %}" target="_blank">太极</a>

</h2>
<h2>
    <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
    <span>::</span>

    <a href="{% url 'blog:game_2048' %}" target="_blank">2048小游戏</a>
    </h2>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的文字</title>
</head>
<body>
<h1>文章列表</h1>
<span>--------------------------------------</span>
<br>
{% for article in articles %}
    <h2><a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a></h2>
        <!--<a href="{% url 'blog:edit_delete' article.id %}">删除</a></h2>-->
{% endfor %}<br>
<span>--------------------------------------</span>
<h1><a href="{% url 'blog:edit_page'%}">新文章</a></h1>
</body>
</html>

myblog/blog/templates/blog/machine_learn.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>机器学习</title>
</head>
<body>
<h1>机器学习与算法课程相关链接</h1>
<ul>
    <li>吴恩达教授斯坦福大学公开课 <br><a href="http://open.163.com/special/opencourse/machinelearning.html">点击</a></li>
    <li>人工智能实践：Tensorflow笔记 <br><a href="https://www.icourse163.org/course/PKU-1002536002">点击</a></li>
    <li>麻省理工学院公开课：算法导论 <br><a href="https://www.bilibili.com/video/av1149902?from=search&seid=2340808155580412135">点击</a></li>
</ul>
</body>
</html>

myblog/blog/templates/blog/weather.html
<!DOCTYPE html>
<html>
<head>
	<title>weather</title>
</head>
<style type="text/css">
	.main{ margin: 50px auto; width: 300px ; height: 200px; }
</style>
<body>
	<div class="main">
		<iframe scrolling="no" src="https://tianqiapi.com/api.php?style=tr&skin=pitaya" frameborder="0" width="325" height="220" allowtransparency="true"></iframe>
	</div>

</body>
</html>